FROM alpine:3.8

ENV CURATOR_VERSION=5.5.4

RUN apk --update add --no-cache tini python py-pip \
  && pip install elasticsearch-curator==${CURATOR_VERSION}

COPY curator-entrypoint.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh

WORKDIR /usr/share/curator

ENTRYPOINT ["/entrypoint.sh"]
